spring:
  datasource:
    url: jdbc:h2:mem:reserve_me_db
    driverClassName: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /api/h2-console
      # settings:
      #   web-allow-others: true  
  sql:
    init:
      data-locations: classpath:data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
image:
  upload:
    directory: C:\reserveme\images\
  cdn:
    url: http://localhost:8080/api/files