export const FOOD_VENDORS = [
    'Restaurant',
    'Tacos stand',
    'Pizza parlor',
    'Food truck',
    'Ice cream truck',
    'Coffee shop',
    'Bakery',
    'Cafeteria',
    'Food court',
    'Sandwich shop',
    'Burger joint',
    'Sushi bar',
    'Thai food stall',
    'BBQ smokehouse',
    'Juice bar',
    'Salad bar',
    'Hot dog stand',
    'Donut shop',
    'Indian curry house',
    'Vegetarian/vegan eatery',
    'Seafood restaurant',
    'Chinese takeout',
    'French bistro',
    'Italian trattoria',
    'Mexican cantina',
    'Greek taverna',
    'Ramen shop',
    'Vietnamese pho stall',
    'Spanish tapas bar',
    'Middle Eastern falafel stand',
    'Brazilian churrascaria',
    'Korean BBQ joint',
    'Jamaican jerk chicken stall',
    'Ethiopian injera cafe',
    'Peruvian cevicheria',
    'Lebanese shawarma spot',
    'German beer garden',
    'Malaysian hawker center',
    'Colombian arepa vendor',
    'Cuban sandwich shop',
]